### ISSUE TITLE
Prob bib

### ISSUE THREAD

**Issue by BGTheodore** [BGTheodore/GeoTech#70]
Pour eviter que JE cree encore des conflits...
Ya un prob dans les fichiers .bib auxquels je n'ai pas touches

**Comment by BGTheodore** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Probleme Latech](https://trello.com/c/fYTAkvpc/74-probleme-latech)

**Comment by kevindubuche** [comment]
Des fois les accents (é,è) nous font la guerre. We'll them all at the end.
